apiVersion: v1
kind: Service
metadata:
  name: video-manager-api
  namespace: video-platform
spec:
  selector:
    app: video-manager-api
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP