export const ErrorCodes = {
  // Storage
  STORAGE_INIT_FAILED: "STORAGE_INIT_FAILED",
  STORAGE_UPLOAD_FAILED: "STORAGE_UPLOAD_FAILED",
  STORAGE_COMPLETE_FAILED: "STORAGE_COMPLETE_FAILED",

  // Cache
  CACHE_SET_FAILED: "CACHE_SET_FAILED",
  CACHE_GET_FAILED: "CACHE_GET_FAILED",

  // Video
  VIDEO_NOT_FOUND: "VIDEO_NOT_FOUND",
  VIDEO_SAVE_FAILED: "VIDEO_SAVE_FAILED",

  // Upload
  UPLOAD_NOT_FOUND: "UPLOAD_NOT_FOUND",
  UPLOAD_ALREADY_COMPLETE: "UPLOAD_ALREADY_COMPLETE",
  UPLOAD_CHUNK_FAILED: "UPLOAD_CHUNK_FAILED",
} as const
