export const ErrorCodes = {
  STORAGE_INIT_FAILED: "STORAGE_INIT_FAILED",
  STORAGE_UPLOAD_FAILED: "STORAGE_UPLOAD_FAILED",
  STORAGE_COMPLETE_FAILED: "STORAGE_COMPLETE_FAILED",
  STORAGE_PRESIGN_FAILED: "STORAGE_PRESIGN_FAILED",

  CACHE_SET_FAILED: "CACHE_SET_FAILED",
  CACHE_GET_FAILED: "CACHE_GET_FAILED",

  VIDEO_NOT_FOUND: "VIDEO_NOT_FOUND",
  VIDEO_SAVE_FAILED: "VIDEO_SAVE_FAILED",

  UPLOAD_NOT_FOUND: "UPLOAD_NOT_FOUND",
  UPLOAD_ALREADY_COMPLETE: "UPLOAD_ALREADY_COMPLETE",
  UPLOAD_CHUNK_FAILED: "UPLOAD_CHUNK_FAILED",
  UPLOAD_INCOMPLETE: "UPLOAD_INCOMPLETE",
  UPLOAD_SESSION_MISMATCH: "UPLOAD_SESSION_MISMATCH",
  UPLOAD_INVALID_PART: "UPLOAD_INVALID_PART",

  QUEUE_PUBLISH_FAILED: "QUEUE_PUBLISH_FAILED",
} as const;
