name: Backend Dev

on:
  push:
    branches-ignore:
      - master

jobs:
  deploy:
    name: Build and Deploy Backend
    runs-on: ubuntu-latest
    environment: DEV

    if: contains(github.event.head_commit.message, '#deploydev')

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: us-east-1

      - name: Login no ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build e Push imagem Docker
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: dev-video-manager-api
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name dev-video-cluster \
            --region us-east-1

            - name: Apply Kubernetes manifests
            run: |
              kubectl apply -f k8s/namespace.yaml
              kubectl apply -f k8s/configmap.yaml
              kubectl apply -f k8s/deployment.yaml
              kubectl apply -f k8s/service.yaml

          - name: Cria Kubernetes Secret
            run: |
              kubectl create secret generic video-manager-api-secrets \
                --namespace=video-platform \
                --from-literal=DATABASE_URL=postgresql://${{ secrets.DB_USERNAME }}:${{ secrets.DB_PASSWORD }}@dev-video-postgres.ccrakaw6cjoa.us-east-1.rds.amazonaws.com:5432/videoplatform \
                --dry-run=client -o yaml | kubectl apply -f -

      - name: Update imagem no deployment
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          kubectl set image deployment/video-manager-api \
            video-manager-api=$ECR_REGISTRY/dev-video-manager-api:$IMAGE_TAG \
            -n video-platform

      - name: Aguarda rollout
        run: |
          kubectl rollout status deployment/video-manager-api \
            -n video-platform \
            --timeout=120s
